# Generated by Django 6.0.7 on 2026-07-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
